[tool.poetry]
name = "pine"
version = "0.1.0"
description = "A simple logging tool."
authors = ["Avneesh Chandra"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
datetime = "^5.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
